/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRegistration;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Hospital.Organization.PatientOrganization;
import Business.Hospital.Organization.ReceptionistOrganization;
import Business.Network.Network;
import Business.Organization.Organization;
import UserInterface.MainJFrame;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pushkar
 */
public class SelectNetworkForm extends javax.swing.JPanel {

    /**
     * Creates new form SelectNetworkForm
     */
    private ArrayList<Network> networks;
    private JPanel userProcessContainer;
    private MainJFrame main;

    public SelectNetworkForm(JPanel userProcessContainer, ArrayList<Network> networkList, MainJFrame main) {

        initComponents();
        this.main = main;
        this.networks = networkList;
        this.userProcessContainer = userProcessContainer;
        populateNetwork();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        ddlNetwork = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 102, 102));
        lblTitle.setText("SELECT NETWORK");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 290, 32));

        add(ddlNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 170, 30));

        btnSubmit.setText("Select");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    public void populateNetwork() {
        ddlNetwork.removeAllItems();
        ddlNetwork.addItem("Select");
        for (Network network : networks) {
            ddlNetwork.addItem(network);
        }
    }

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (!ddlNetwork.getSelectedItem().equals("Select")) {
            Network network = (Network) ddlNetwork.getSelectedItem();
            Enterprise erp = null;
            Organization org = null;
            Organization rec = null;
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HospitalEnterprise) {
                    erp = enterprise;
                    for (Organization organization : erp.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof ReceptionistOrganization) {
                            rec = organization;
                            break;
                        }
                    }
                    for (Organization organ : erp.getOrganizationDirectory().getOrganizationList()) {
                        if (organ instanceof PatientOrganization) {
                            org = organ;
                            break;
                        }
                    }
                    break;
                }

            }
            if (erp != null && org != null && rec != null) {
                PatientRegistrationForm prf = new PatientRegistrationForm(userProcessContainer, (HospitalEnterprise) erp, (PatientOrganization) org, main);
                userProcessContainer.add("SelectNetwork", prf);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else {
                lblMessage.setText("Sorry. We are not available in your region.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a network.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox ddlNetwork;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
