/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NurseRole;

import Business.Enterprise.HospitalEnterprise;
import Business.Hospital.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Patient.PatientVisit;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DiseaseEvaluationWorkRequest;
import Business.WorkQueue.DocumentVitalsWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DrugTrialRole.ManageDrugTrial;

/**
 *
 * @author vivekshetye
 */
public class PatientEvaluation extends javax.swing.JPanel {

    JPanel userProcessContainer;
    DocumentVitalsWorkRequest request;
    Patient patient;
    PatientVisit patientVisit;
    UserAccount account;
    HospitalEnterprise hospitalEnterprise;

    /**
     * Creates new form PatientEvaluation
     *
     * @param userProcessContainer
     * @param rwr
     * @param account
     */
    public PatientEvaluation(JPanel userProcessContainer, DocumentVitalsWorkRequest rwr, UserAccount account, HospitalEnterprise hospitalEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.hospitalEnterprise = hospitalEnterprise;
        this.request = rwr;
        this.patient = rwr.getPatient();
        this.patientVisit = rwr.getPatientVisit();
        populateForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblSymptoms = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtSymptoms = new javax.swing.JTextField();
        btnSendReport = new javax.swing.JButton();
        lblBodyTemp = new javax.swing.JLabel();
        lblPulseRatte = new javax.swing.JLabel();
        lblRespRate = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        txtRespRate = new javax.swing.JTextField();
        txtPulseRate = new javax.swing.JTextField();
        txtBodyTemp = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Patient Evaluation");

        lblPatientName.setText("Patient name:");

        lblAge.setText("Age:");

        lblGender.setText("Gender:");

        lblSymptoms.setText("Symptoms:");

        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtSymptoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSymptomsActionPerformed(evt);
            }
        });

        btnSendReport.setText("Send Report");
        btnSendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReportActionPerformed(evt);
            }
        });

        lblBodyTemp.setText("Body temperature:");

        lblPulseRatte.setText("Pulse rate:");

        lblRespRate.setText("Respiration rate:");

        lblBloodPressure.setText("Blood Pressure");

        txtRespRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespRateActionPerformed(evt);
            }
        });

        txtPulseRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPulseRateActionPerformed(evt);
            }
        });

        txtBodyTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodyTempActionPerformed(evt);
            }
        });

        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblTitle))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(118, 118, 118)
                            .addComponent(btnSendReport))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAge)
                                .addComponent(lblPatientName)
                                .addComponent(lblGender)
                                .addComponent(lblSymptoms)
                                .addComponent(lblBloodPressure)
                                .addComponent(lblRespRate)
                                .addComponent(lblPulseRatte)
                                .addComponent(lblBodyTemp))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblTitle)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSymptoms)
                    .addComponent(txtSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBodyTemp)
                    .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulseRatte)
                    .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespRate)
                    .addComponent(txtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodPressure)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendReport)
                    .addComponent(btnBack))
                .addGap(205, 205, 205))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtSymptomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSymptomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSymptomsActionPerformed

    public boolean validateData() {
        if (txtRespRate.getText().trim().equals("")
                || txtSymptoms.getText().trim().equals("")
                || txtBloodPressure.getText().trim().equals("")
                || txtBodyTemp.getText().trim().equals("") || txtPulseRate.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtSymptoms.getText().trim().matches("[a-zA-Z ,]+")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid symptoms.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtBodyTemp.getText().trim().matches("[0-9]{1,13}(\\.[0-9]*)?") || !(Double.parseDouble(txtBodyTemp.getText()) >= 95 && Double.parseDouble(txtBodyTemp.getText()) <= 102)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid body teperature(95-100).", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtPulseRate.getText().trim().matches("[0-9]{1,13}(\\.[0-9]*)?") || !(Double.parseDouble(txtPulseRate.getText()) >= 50 && Double.parseDouble(txtPulseRate.getText()) <= 110)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid pulse rate(50-110).", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtRespRate.getText().trim().matches("[0-9]{1,13}(\\.[0-9]*)?") || !(Double.parseDouble(txtRespRate.getText()) >= 10 && Double.parseDouble(txtRespRate.getText()) <= 23)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid respiratory rate(10-23).", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!txtBloodPressure.getText().trim().matches("[0-9]{1,13}(\\.[0-9]*)?") || !(Double.parseDouble(txtBloodPressure.getText()) >= 85 && Double.parseDouble(txtBloodPressure.getText()) <= 135)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid blood pressure(85-135).", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    private void btnSendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReportActionPerformed
        // TODO add your handling code here:

        if (validateData()) {

            patientVisit.setSymptoms(txtSymptoms.getText());
            patientVisit.getVitalSigns().setBloodPressure(Double.parseDouble(txtBloodPressure.getText()));
            patientVisit.getVitalSigns().setBodyTemperature(Double.parseDouble(txtBodyTemp.getText()));
            patientVisit.getVitalSigns().setPulseRate(Double.parseDouble(txtPulseRate.getText()));
            patientVisit.getVitalSigns().setRespirationRate(Double.parseDouble(txtRespRate.getText()));

            DiseaseEvaluationWorkRequest diseaseRequest = new DiseaseEvaluationWorkRequest();
            diseaseRequest.setPatient(patient);
            diseaseRequest.setPatientVisit(patientVisit);
            diseaseRequest.setSender(account);
            diseaseRequest.setStatus("Sent");

            Organization organization = null;
            for (Organization org : hospitalEnterprise.getOrganizationDirectory().getOrganizationList()) {

                if (org instanceof DoctorOrganization) {
                    organization = org;

                    break;
                }
            }
            organization.getWorkQueue().getWorkRequestList().add(diseaseRequest);
            account.getWorkQueue().getWorkRequestList().add(diseaseRequest);
        }


    }//GEN-LAST:event_btnSendReportActionPerformed

    private void txtRespRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespRateActionPerformed

    private void txtPulseRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPulseRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulseRateActionPerformed

    private void txtBodyTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodyTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodyTempActionPerformed

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NurseWorkAreaJPanel panel = (NurseWorkAreaJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendReport;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblBodyTemp;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPulseRatte;
    private javax.swing.JLabel lblRespRate;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtBodyTemp;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPulseRate;
    private javax.swing.JTextField txtRespRate;
    private javax.swing.JTextField txtSymptoms;
    // End of variables declaration//GEN-END:variables

    private void populateForm() {
        txtPatientName.setText(patient.getName());
        txtAge.setText(String.valueOf(patient.getAge()));
        txtGender.setText(patient.getGender().toString());
        txtPatientName.setEnabled(false);
        txtAge.setEnabled(false);
        txtGender.setEnabled(false);

    }
}
