/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugTrialRole;

import Business.DrugManufacturing.Organization.DrugTrialOrganization;
import Business.Enterprise.DrugManufacturingEnterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mihir
 */
public class DrugTrialWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugTrialWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    DrugTrialOrganization drugTrialOrganization;
    DrugManufacturingEnterprise drugManufacturingEnterprise;
    Network network;

    public DrugTrialWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DrugTrialOrganization drugTrialOrganization, DrugManufacturingEnterprise drugManufacturingEnterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.account = account;
        this.drugTrialOrganization = drugTrialOrganization;
        this.drugManufacturingEnterprise = drugManufacturingEnterprise;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        btnIND = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 102, 102));
        lblTitle.setText("DRUG TRIAL WORK AREA");

        btnRequest.setText("Manage Drug Trials");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnIND.setText("Send to FDA");
        btnIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnIND, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(232, 232, 232))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequest)
                    .addComponent(btnIND))
                .addGap(351, 351, 351))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        ManageDrugTrial mdt = new ManageDrugTrial(userProcessContainer, drugTrialOrganization, drugManufacturingEnterprise, account);
        userProcessContainer.add("ProcureCompounds", mdt);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINDActionPerformed
        ManageFDAApplications mfda = new ManageFDAApplications(userProcessContainer, account, drugTrialOrganization, drugManufacturingEnterprise, network);
        userProcessContainer.add("ManageFDAApplications", mfda);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnINDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIND;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
