/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugTrialRole;

import Business.Drug.DrugVersions;
import Business.Drug.Drugs;
import Business.DrugManufacturing.Organization.DrugTrialOrganization;
import Business.Enterprise.DrugManufacturingEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FDAEnterprise;
import Business.FDA.Organization.DrugEvaluationOrganization;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DrugEvaluationWorkRequest;
import Business.WorkQueue.DrugTrialWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pushkar
 */
public class ManageFDAApplications extends javax.swing.JPanel {

    /**
     * Creates new form ManageFDAApplications
     */
    JPanel userProcessContainer;
    UserAccount account;
    DrugTrialOrganization drugTrialOrganization;
    DrugManufacturingEnterprise drugManufacturingEnterprise;
    Network network;

    public ManageFDAApplications(JPanel userProcessContainer, UserAccount account, DrugTrialOrganization drugTrialOrganization, DrugManufacturingEnterprise drugManufacturingEnterprise, Network network) {
        initComponents();
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.drugManufacturingEnterprise = drugManufacturingEnterprise;
        this.drugTrialOrganization = drugTrialOrganization;
        this.network = network;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApprovedDrugs = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Manage FDA Applications");

        tblApprovedDrugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug", "Version", "Disease", "Sent to FDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblApprovedDrugs);
        if (tblApprovedDrugs.getColumnModel().getColumnCount() > 0) {
            tblApprovedDrugs.getColumnModel().getColumn(0).setResizable(false);
            tblApprovedDrugs.getColumnModel().getColumn(1).setResizable(false);
            tblApprovedDrugs.getColumnModel().getColumn(2).setResizable(false);
            tblApprovedDrugs.getColumnModel().getColumn(3).setResizable(false);
        }

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRequest))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(jLabel1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)))
                .addGap(197, 197, 197))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblApprovedDrugs.getSelectedRow();
        if (selectedrow < 0) {
            JOptionPane.showMessageDialog(this, "Select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            DrugEvaluationWorkRequest drugEvaluationWorkRequest = new DrugEvaluationWorkRequest();
            drugEvaluationWorkRequest.setDrug((Drugs) tblApprovedDrugs.getValueAt(selectedrow, 0));
            drugEvaluationWorkRequest.setDrugVersions((DrugVersions) tblApprovedDrugs.getValueAt(selectedrow, 1));
            drugEvaluationWorkRequest.setSender(account);
            drugEvaluationWorkRequest.setStatus("Sent");

            Organization organization = null;
            for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {

                if (ent instanceof FDAEnterprise) {

                    for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                        if (org instanceof DrugEvaluationOrganization) {
                            organization = org;
                            break;
                        }
                    }
                    break;
                }
            }

            organization.getWorkQueue().getWorkRequestList().add(drugEvaluationWorkRequest);
            account.getWorkQueue().getWorkRequestList().add(drugEvaluationWorkRequest);
        }
        populateTable();
    }//GEN-LAST:event_btnRequestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblApprovedDrugs.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : drugTrialOrganization.getWorkQueue().getWorkRequestList()) {

            if (((DrugTrialWorkRequest) request).getDrugVersions().isApproved()) {
                Object[] row = new Object[4];

                row[0] = ((DrugTrialWorkRequest) request).getDrug();
                row[1] = ((DrugTrialWorkRequest) request).getDrugVersions();
                row[2] = ((DrugTrialWorkRequest) request).getDisease();
                row[3] = checkSentStatus(((DrugTrialWorkRequest) request).getDrugVersions());

                dtm.addRow(row);
            }
        }
    }

    public String checkSentStatus(DrugVersions drugVersions) {

        Organization organization = null;
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {

            if (ent instanceof FDAEnterprise) {

                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {

                    if (org instanceof DrugEvaluationOrganization) {
                        organization = org;
                        break;
                    }
                }
                break;
            }
        }

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (((DrugEvaluationWorkRequest) request).getDrugVersions() == drugVersions) {
                return "Sent";
            }
        }

        return "Not yet";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblApprovedDrugs;
    // End of variables declaration//GEN-END:variables
}
