/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Disease.Disease;
import Business.Disease.DiseaseDirectory;
import Business.Drug.ApprovedDrugsDirectory;
import Business.DrugOrders.DrugItems;
import Business.Enterprise.HospitalEnterprise;

import Business.Hospital.Organization.PatientOrganization;
import Business.Patient.Patient;

import Business.Organization.Organization;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.DiseaseEvaluationWorkRequest;
import Business.WorkQueue.PrescriptionWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import userinterface.DrugEvaluationRole.ReviewApplictions;

/**
 *
 * @author vivekshetye
 */
public class DoctorTreatmentAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorTreatmentAreaPanel
     */
    JPanel userProcessContainer;
    DiseaseEvaluationWorkRequest dew;
    UserAccount account;
    ApprovedDrugsDirectory approvedDrugsDirectory;
    HospitalEnterprise hospitalEnterprise;
    DiseaseDirectory diseaseDirectory;

    //add whole drug directory
    public DoctorTreatmentAreaPanel(JPanel userProcessContainer, UserAccount account, DiseaseEvaluationWorkRequest dew, HospitalEnterprise hospitalEnterprise, DiseaseDirectory diseaseDirectory, ApprovedDrugsDirectory approvedDrugsDirectory) {
        initComponents();
        this.diseaseDirectory = diseaseDirectory;
        this.userProcessContainer = userProcessContainer;
        this.dew = dew;
        this.account = account;
        this.approvedDrugsDirectory = approvedDrugsDirectory;
        this.hospitalEnterprise = hospitalEnterprise;
        populateCombo();
        setFields();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbDisease = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbDrug = new javax.swing.JComboBox();
        btnDiagnose = new javax.swing.JButton();
        lblPulseRatte = new javax.swing.JLabel();
        lblBodyTemp = new javax.swing.JLabel();
        lblRespRate = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblSymptoms = new javax.swing.JLabel();
        txtRespRate = new javax.swing.JTextField();
        txtPulseRate = new javax.swing.JTextField();
        txtBodyTemp = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        txtSymptoms = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Doctor Treatment Panel");

        lblPatientName.setText("Patient name:");

        lblGender.setText("Gender:");

        lblAge.setText("Age:");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        jLabel2.setText("Disease:");

        cmbDisease.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDisease.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDiseaseItemStateChanged(evt);
            }
        });
        cmbDisease.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmbDiseaseInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        cmbDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiseaseActionPerformed(evt);
            }
        });

        jLabel3.setText("Drug:");

        cmbDrug.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDrugItemStateChanged(evt);
            }
        });
        cmbDrug.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmbDrugInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        btnDiagnose.setText("Diagnose");
        btnDiagnose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnoseActionPerformed(evt);
            }
        });

        lblPulseRatte.setText("Pulse rate:");

        lblBodyTemp.setText("Body temperature:");

        lblRespRate.setText("Respiration rate:");

        lblBloodPressure.setText("Blood Pressure");

        lblSymptoms.setText("Symptoms:");

        txtRespRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespRateActionPerformed(evt);
            }
        });

        txtPulseRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPulseRateActionPerformed(evt);
            }
        });

        txtBodyTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodyTempActionPerformed(evt);
            }
        });

        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });

        txtSymptoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSymptomsActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantity:");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAge)
                                    .addComponent(lblGender)
                                    .addComponent(lblSymptoms))
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPatientName)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPatientName)
                                .addComponent(txtGender)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBloodPressure)
                            .addComponent(lblPulseRatte)
                            .addComponent(lblBodyTemp)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnDiagnose)
                                .addComponent(lblRespRate)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnBack))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBodyTemp)
                            .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPulseRatte)
                            .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRespRate)
                            .addComponent(txtRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodPressure)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientName))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSymptoms)
                            .addComponent(txtSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiagnose)
                    .addComponent(btnBack))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setFields() {
        txtPatientName.setText(dew.getPatient().getName());
        txtAge.setText(String.valueOf(dew.getPatient().getAge()));
        txtGender.setText(String.valueOf(dew.getPatient().getGender()));
        txtBloodPressure.setText(String.valueOf(dew.getPatientVisit().getVitalSigns().getBloodPressure()));
        txtBodyTemp.setText(String.valueOf(dew.getPatientVisit().getVitalSigns().getBodyTemperature()));
        txtPulseRate.setText(String.valueOf(dew.getPatientVisit().getVitalSigns().getPulseRate()));
        txtRespRate.setText(String.valueOf(dew.getPatientVisit().getVitalSigns().getPulseRate()));
        txtSymptoms.setText(String.valueOf(dew.getPatientVisit().getSymptoms()));
        
        txtAge.setEnabled(false);
        txtBloodPressure.setEnabled(false);
        txtBodyTemp.setEnabled(false);
        txtGender.setEnabled(false);
        txtPatientName.setEnabled(false);
        txtPulseRate.setEnabled(false);
        txtRespRate.setEnabled(false);
        txtSymptoms.setEnabled(false);
    }
    
    public void populateCombo() {
        cmbDisease.removeAllItems();
        cmbDisease.addItem("Select");
        for (Disease disease : diseaseDirectory.getDiseaseList()) {
            cmbDisease.addItem(disease);
        }
        if(cmbDrug.getItemCount() == 1) {
            cmbDisease.removeAllItems();
        }

        
    }
    
    public void populateDrugCombo(Disease disease) {
        cmbDrug.removeAllItems();
        cmbDrug.addItem("Select");
        for (DrugItems drugItems : approvedDrugsDirectory.getApprovedDrugs()) {
            if(disease.getName().equals(drugItems.getDrug().getDisease()))
            {
                
            cmbDrug.addItem(drugItems);
            }
        }
    }
    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void btnDiagnoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnoseActionPerformed
        // TODO add your handling code here:

        PrescriptionWorkRequest request = new PrescriptionWorkRequest();

        request.setDrugItems((DrugItems) cmbDrug.getSelectedItem());
        request.setSender(account);
        request.setStatus("Sent");
        request.setQuantity(Integer.parseInt(txtQuantity.getText()));

        Organization organization = null;
        UserAccount ua = null;
        for (Organization org : hospitalEnterprise.getOrganizationDirectory().getOrganizationList()) {

            if (org instanceof PatientOrganization) {
                organization = org;
                break;
            }
        }

        for (UserAccount user : ((PatientOrganization) organization).getUserAccountDirectory().getUserAccountList()) {

            if ((Patient) user.getPerson() == dew.getPatient()) {
                user.getWorkQueue().getWorkRequestList().add(request);
            }
        }
        account.getWorkQueue().getWorkRequestList().add(request);
    }//GEN-LAST:event_btnDiagnoseActionPerformed

    private void txtRespRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespRateActionPerformed

    private void txtPulseRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPulseRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulseRateActionPerformed

    private void txtBodyTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodyTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodyTempActionPerformed

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void txtSymptomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSymptomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSymptomsActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void cmbDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiseaseActionPerformed
        // TODO add your handling code here:
        if(cmbDisease.getSelectedIndex() > 0) {
            Disease disease = (Disease) cmbDisease.getSelectedItem();
            populateDrugCombo(disease);
        }
        
    }//GEN-LAST:event_cmbDiseaseActionPerformed

    private void cmbDiseaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDiseaseItemStateChanged
        // TODO add your handling code here:
        
        if(cmbDisease.getSelectedIndex() > 0) {
            Disease disease = (Disease) cmbDisease.getSelectedItem();
            populateDrugCombo(disease);
        }
        
    }//GEN-LAST:event_cmbDiseaseItemStateChanged

    private void cmbDrugItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDrugItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDrugItemStateChanged

    private void cmbDrugInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmbDrugInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDrugInputMethodTextChanged

    private void cmbDiseaseInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmbDiseaseInputMethodTextChanged
        // TODO add your handling code here:
       if(cmbDisease.getSelectedIndex() > 0) {
            Disease disease = (Disease) cmbDisease.getSelectedItem();
            populateDrugCombo(disease);
        }
    }//GEN-LAST:event_cmbDiseaseInputMethodTextChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel panel = (DoctorWorkAreaJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDiagnose;
    private javax.swing.JComboBox cmbDisease;
    private javax.swing.JComboBox cmbDrug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblBodyTemp;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPulseRatte;
    private javax.swing.JLabel lblRespRate;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtBodyTemp;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPulseRate;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRespRate;
    private javax.swing.JTextField txtSymptoms;
    // End of variables declaration//GEN-END:variables
}
