/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.DrugOrders.DrugItems;
import Business.Enterprise.HospitalEnterprise;
import Business.Hospital.Organization.LocalPharmacyOrganization;
import Business.Hospital.Organization.PatientOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientDrugRequest;
import Business.WorkQueue.PrescriptionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.DrugTrialRole.ManageDrugTrial;

/**
 *
 * @author vivekshetye
 */
public class RequestPrescribedDrugs extends javax.swing.JPanel {

    /**
     * Creates new form RequestPrescribedDrugs
     */
    JPanel userProcessContainer;
    UserAccount account;
    PatientOrganization patientOrganization;
    HospitalEnterprise hospitalEnterprise;
     

    public RequestPrescribedDrugs(JPanel userProcessContainer, UserAccount account, PatientOrganization patientOrganization, HospitalEnterprise hospitalEnterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.patientOrganization = patientOrganization;
        this.hospitalEnterprise = hospitalEnterprise;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrescDrugs = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("PRESCRIBED DRUGS");

        tblPrescDrugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Drug Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrescDrugs.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPrescDrugs);
        if (tblPrescDrugs.getColumnModel().getColumnCount() > 0) {
            tblPrescDrugs.getColumnModel().getColumn(0).setResizable(false);
            tblPrescDrugs.getColumnModel().getColumn(1).setResizable(false);
            tblPrescDrugs.getColumnModel().getColumn(2).setResizable(false);
            tblPrescDrugs.getColumnModel().getColumn(3).setResizable(false);
        }

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(308, 308, 308)
                        .addComponent(btnRequest))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jLabel1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequest)
                    .addComponent(btnBack))
                .addGap(324, 324, 324))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable() {
        
        DefaultTableModel dtm = (DefaultTableModel) tblPrescDrugs.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
         
            if(request instanceof PrescriptionWorkRequest) {
            Object[] row = new Object[4];
            row[0] = (PrescriptionWorkRequest) request;
            row[1] = ((PrescriptionWorkRequest) request).getDrugItems();
            row[2] = ((PrescriptionWorkRequest) request).getQuantity();
            row[3] = ((PrescriptionWorkRequest) request).getDrugItems().getSellingPrice() * ((PrescriptionWorkRequest) request).getQuantity();
            
            dtm.addRow(row);
        }
        }
    }
    
    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblPrescDrugs.getSelectedRow();
        
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
            
        } else {
            
            PatientDrugRequest pdr = new PatientDrugRequest();
            
            PrescriptionWorkRequest pwr = (PrescriptionWorkRequest) tblPrescDrugs.getValueAt(selectedRow, 0);
            
            pdr.setDrugItems(pwr.getDrugItems());
            pdr.setQuantity(pwr.getQuantity());
            pdr.setSender(account);
            pdr.setStatus("Pending");
            
            Organization organization = null;
            for(Organization org : hospitalEnterprise.getOrganizationDirectory().getOrganizationList()) {
                
                if(org instanceof LocalPharmacyOrganization)
                {
                    organization = org;
                    break;
                }
            }
            
            organization.getWorkQueue().getWorkRequestList().add(pdr);
            account.getWorkQueue().getWorkRequestList().add(pdr);
            
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrescDrugs;
    // End of variables declaration//GEN-END:variables
}
